import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { JetBrains_Mono } from "next/font/google";
import {Noto_Sans_Egyptian_Hieroglyphs} from "next/font/google";
import { Dancing_Script } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const jetbrainsMono=JetBrains_Mono({subsets:["latin"],
  weight:["100","200","300","400","500","600","700","800"],
  variable:"--font-jetbrainsMono"
})

const egyptGlyphs=Noto_Sans_Egyptian_Hieroglyphs({
  subsets:["egyptian-hieroglyphs"],
  weight:["400"],
  variable:"--font-egyptGlyphs"
})

const dancingScript=Dancing_Script({
  subsets:["latin"],
  weight:["400","500","600","700"],
  variable:"--font-dancingScript"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className={`${jetbrainsMono.variable} antialiased`}
        className={`${jetbrainsMono.variable} ${egyptGlyphs.variable} antialiased`}
      >
        <Header />
        <StairTransition />
        <PageTransition>
        {children}
        </PageTransition>
      </body>
    </html>
  );
}
